gen: src/gen/* src/gen/lr/parse_template.go
	go build gen

src/gen/lr/parse_template.go: src/gen/lr/_parse_template.go
	( echo 'package lr' && \
	echo '// this file autogenerated from $<, do not edit' && \
	echo 'const parseTemplate = `' && \
	cat $< && \
	echo '`' ) > $@
